name: sonify
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  tflite_flutter: ^0.11.0
  share_plus: ^10.1.4
  just_audio: ^0.9.46
  flutter_tts: ^4.2.2
  # Native splash packages removed

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true