name: sonify
description: "Sonify — offline text-to-speech app powered by Piper AI."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  path_provider: ^2.1.5
  path: ^1.9.0
  uuid: ^4.5.1
  intl: ^0.20.2
  share_plus: ^10.1.4
  just_audio: ^0.9.46
  get_it: ^8.0.2
  sherpa_onnx: ^1.12.31
  archive: ^4.0.9
  background_downloader: ^9.5.4
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sonify-logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#1A3684"
  adaptive_icon_foreground: "assets/images/sonify-logo.png"

flutter:
  generate: true

  assets:
    - assets/images/
    - assets/espeak-ng-data/
    - assets/tts-model/vits-piper-en_US-lessac-medium/
    - assets/tts-model/vits-piper-ar_JO-kareem-medium/
    - assets/tts-model/vits-piper-en_US-ryan-medium/

  uses-material-design: true