// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSrNr4VocCm-P79Bpii5jm0us7OHN0fKg',
    appId: '1:392705200270:web:2d30c5116ea03c342cf9df',
    messagingSenderId: '392705200270',
    projectId: 'sonify-4cb94',
    authDomain: 'sonify-4cb94.firebaseapp.com',
    storageBucket: 'sonify-4cb94.firebasestorage.app',
    measurementId: 'G-KXB5FZBK26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC-S9yoF9n3U5JrcT2lSnE2QSaitseg8o',
    appId: '1:392705200270:android:cd37ea98bf33700b2cf9df',
    messagingSenderId: '392705200270',
    projectId: 'sonify-4cb94',
    storageBucket: 'sonify-4cb94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhzAZxrhzzJVRSzDU7cMrrNYd8fUJVa6k',
    appId: '1:392705200270:ios:b7c86c71c84613bb2cf9df',
    messagingSenderId: '392705200270',
    projectId: 'sonify-4cb94',
    storageBucket: 'sonify-4cb94.firebasestorage.app',
    iosBundleId: 'com.example.sonify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhzAZxrhzzJVRSzDU7cMrrNYd8fUJVa6k',
    appId: '1:392705200270:ios:b7c86c71c84613bb2cf9df',
    messagingSenderId: '392705200270',
    projectId: 'sonify-4cb94',
    storageBucket: 'sonify-4cb94.firebasestorage.app',
    iosBundleId: 'com.example.sonify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSrNr4VocCm-P79Bpii5jm0us7OHN0fKg',
    appId: '1:392705200270:web:8b6872290e4250172cf9df',
    messagingSenderId: '392705200270',
    projectId: 'sonify-4cb94',
    authDomain: 'sonify-4cb94.firebaseapp.com',
    storageBucket: 'sonify-4cb94.firebasestorage.app',
    measurementId: 'G-ZZPV1DJW5W',
  );

}